services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    restart: always
    
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    volumes:
      - pgadmin-data:/var/lib/pgadmin
   
    ports:
      - "8080:80"
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456 
      - PGADMIN_DEFAULT_EMAIL=gallardo@google.com 

volumes:
  postgres-db:
    external: true
  pgadmin-data:
    external: true
      
  